eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    non-secure-port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: pass1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: health,info

resilience4j:
  circuitbreaker:
    instances:
      externalApi:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 5
  retry:
    instances:
      externalApi:
        maxAttempts: 3
        waitDuration: 200ms
  timelimiter:
    instances:
      externalApi:
        timeoutDuration: 2s

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui